const db = require('../../../models');
const { excelService, pdfService } = require('../../../lib/export');
const datetimeService = require('../../../lib/datetime');
const { ApiError } = require('../../../middleware/errorHandler');
const logger = require('../../../config/logger');

const exportToExcel = async (query, currentUser) => {
  try {
    const whereClause = {
      deleted_at: null
    };
    
    if (query.role) {
      const role = await db.Role.findOne({ where: { role_name: query.role } });
      if (role) {
        whereClause.role = role.role_id;
      }
    }
    
    if (query.is_active !== undefined) {
      whereClause.is_active = query.is_active === 'true';
    }
    
    if (query.email_verified !== undefined) {
      whereClause.email_verified = query.email_verified === 'true';
    }
    
    if (query.search) {
      whereClause[db.Sequelize.Op.or] = [
        { email: { [db.Sequelize.Op.iLike]: `%${query.search}%` } },
        { full_name: { [db.Sequelize.Op.iLike]: `%${query.search}%` } }
      ];
    }
    
    const users = await db.User.findAll({
      where: whereClause,
      include: [{
        model: db.Role,
        as: 'userRole',
        attributes: ['role_name']
      }],
      order: [['created_at', 'DESC']]
    });
    
    const data = users.map(user => ({
      'User ID': user.user_id,
      'Email': user.email,
      'Full Name': user.full_name,
      'Role': user.userRole ? user.userRole.role_name : 'N/A',
      'Active': user.is_active ? 'Yes' : 'No',
      'Email Verified': user.email_verified ? 'Yes' : 'No',
      'Last Login': user.last_login_at ? datetimeService.formatDateTime(user.last_login_at) : 'Never',
      'Created At': datetimeService.formatDateTime(user.created_at),
      'Updated At': datetimeService.formatDateTime(user.updated_at)
    }));
    
    const filename = `users_export_${Date.now()}.xlsx`;
    const buffer = await excelService.generateExcel(data, 'Users');
    
    logger.info(`Users exported to Excel by user ${currentUser.email}`);
    
    return { buffer, filename };
  } catch (error) {
    logger.error('Error exporting users to Excel:', error);
    throw ApiError.internal('Failed to export users to Excel');
  }
};

const exportToPDF = async (query, currentUser) => {
  try {
    const whereClause = {
      deleted_at: null
    };
    
    if (query.role) {
      const role = await db.Role.findOne({ where: { role_name: query.role } });
      if (role) {
        whereClause.role = role.role_id;
      }
    }
    
    if (query.is_active !== undefined) {
      whereClause.is_active = query.is_active === 'true';
    }
    
    if (query.email_verified !== undefined) {
      whereClause.email_verified = query.email_verified === 'true';
    }
    
    if (query.search) {
      whereClause[db.Sequelize.Op.or] = [
        { email: { [db.Sequelize.Op.iLike]: `%${query.search}%` } },
        { full_name: { [db.Sequelize.Op.iLike]: `%${query.search}%` } }
      ];
    }
    
    const users = await db.User.findAll({
      where: whereClause,
      include: [{
        model: db.Role,
        as: 'userRole',
        attributes: ['role_name']
      }],
      order: [['created_at', 'DESC']]
    });
    
    const tableData = users.map(user => [
      user.user_id,
      user.email,
      user.full_name,
      user.userRole ? user.userRole.role_name : 'N/A',
      user.is_active ? 'Yes' : 'No',
      user.email_verified ? 'Yes' : 'No',
      datetimeService.formatDateTime(user.created_at, 'DATE_ONLY')
    ]);
    
    const headers = ['ID', 'Email', 'Name', 'Role', 'Active', 'Verified', 'Created'];
    
    const htmlContent = `
      <h1>Users Report</h1>
      <p>Generated on: ${datetimeService.getCurrentDateTime()}</p>
      <p>Generated by: ${currentUser.email}</p>
      <p>Total Users: ${users.length}</p>
      <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
        <thead>
          <tr style="background-color: #f2f2f2;">
            ${headers.map(h => `<th style="border: 1px solid #ddd; padding: 8px; text-align: left;">${h}</th>`).join('')}
          </tr>
        </thead>
        <tbody>
          ${tableData.map(row => `
            <tr>
              ${row.map(cell => `<td style="border: 1px solid #ddd; padding: 8px;">${cell}</td>`).join('')}
            </tr>
          `).join('')}
        </tbody>
      </table>
    `;
    
    const filename = `users_report_${Date.now()}.pdf`;
    const buffer = await pdfService.generatePDF(htmlContent);
    
    logger.info(`Users exported to PDF by user ${currentUser.email}`);
    
    return { buffer, filename };
  } catch (error) {
    logger.error('Error exporting users to PDF:', error);
    throw ApiError.internal('Failed to export users to PDF');
  }
};

module.exports = {
  exportToExcel,
  exportToPDF
};
